### ISSUE TITLE
Update the Splunkbase app

### ISSUE THREAD

**Issue by TheWoodRanger** [diogofgm/TA-aruba_networks#6]
Splunkbase app is missing a lot of the updates on Github.

**Comment by diogofgm** [comment]
Hi @TheWoodRanger 

Yes, I'm due to release a new version on splunkbase for a while. I've been working to migrate my old CI workflow that I used to use to publish new apps and add-ons releases to splunkbase and use GitHub actions instead. I should be able to publish the new version in the next days/week depending on my day job.

Thanks for reaching out.

**Comment by diogofgm** [comment]
A new version was released to splunkbase here: https://splunkbase.splunk.com/app/4668/
